version: '3.8'

services:
  # PHP-FPM Servisi
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: myapp-php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - myapp-network

  # Nginx Servisi
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: myapp-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - myapp-network

  # MySQL Servisi (İsteğe Bağlı)
  postgres:
    image: postgres:14      # or any preferred version
    container_name: myapp-postgres
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
   postgres-data:
